const userActionTypes = {
  FETCH_USER: "FETCH USER",
  LOGOUT_USER: "LOGOUT USER",
  LOGIN_SUCCESS: "LOGIN SUCCESS",
  GET_ACCESS_TOKEN: "GET ACCESS TOKEN",
  GET_ACCOUNT: "GET BANK ACCOUNTS",
  GET_TRANS:"GET TRANSACTIONS",
  ADD_BUDGET: "ADD BUDGET",
  GET_BUDGET: "GET BUDGET",
  ADD_EXPENSE: "ADD EXPENSE"
};

export default userActionTypes;
