const userActionTypes = {
  FETCH_USER: "FETCH USER",
  LOGOUT_USER: "LOGOUT USER",
  LOGIN_SUCCESS: "LOGIN SUCCESS",
  GET_ACCESS_TOKEN: "GET ACCESS TOKEN",
  GET_ACCOUNT: "GET BANK ACCOUNTS"
};

export default userActionTypes;
