const userActionTypes = {
  FETCH_USER: "FETCH USER",
  LOGOUT_USER: "LOGOUT USER",
  LOGIN_SUCCESS: "LOGIN SUCCESS",
  LOGIN_WITH_GOOGLE: "LOGIN WITH GOOGLE",
  GET_ACCESS_TOKEN: "GET ACCESS TOKEN",
  GET_ACCOUNT: "GET BANK ACCOUNTS",
  GET_EXPENSES: "GET EXPENSES",
  UPDATE_A_EXPENSES: "UPDATE A EXPENSE",
  CREATE_OR_UPDATE_EXPENSES: "CREATE OR UPDATE EXPENSES",
  DELETE_EXPENSE: "DELETE EXPENSE",
  ADD_BUDGET: "ADD BUDGET",
  GET_TRANS: "GET TRANSACTIONS",
  GET_BUDGET: "GET BUDGET",
  ADD_EXPENSE: "ADD EXPENSE",
  GET_BUDGET_NAMES: "GET BUDGET NAMES",
  DELETE_A_BUDGET: "DELETE A BUDGET",
};

export default userActionTypes;
